apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app-ws-prod
  name: my-app-ws-prod
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30826
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app-ws-prod
  sessionAffinity: None
  type: LoadBalancer
