apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app-ws
  name: my-app-ws
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30825
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-app-ws
  sessionAffinity: None
  type: NodePort
