apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myappws-postgresql
  name: myappws-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myappws-postgresql
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myappws-postgresql
    spec:
      containers:
      - image: myappws-postgresql:12.3
        imagePullPolicy: IfNotPresent
        name: myappws-postgresql
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
