apiVersion: v1
kind: Service
metadata:
  labels:
    app: myappws-postgresql
  name: myappws-postgresql
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 5432
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: myappws-postgresql
  sessionAffinity: None
  type: NodePort
