apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres-container
    tier: backend
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: ClientIP
